server:
  port: 8888
spring:
  application:
    name: apollo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lucasgdamascena/microservice-config
          search-paths: 'greeting-service*'
        default-label: main